#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "ChromeOS" --class "brunch" {
	img_part=/dev/sda13
	img_path=/chromeos.img
	img_uuid=03d60467-4cc2-405d-8c77-23b09c1a8380
	search --no-floppy --set=root --file $img_path
	loopback loop $img_path
#	source (loop,12)/efi/boot/settings.cfg
#	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
#		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
#			cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path \
#			console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
#	else
#		linux (loop,7)$kernel boot=local noresume noswap loglevel=7 options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
#			cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
#	fi
	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 disablevmx=off \
		cros_secure cros_debug enforce_hyperthreading=1 loop.max_part=16
		options=enable_updates,suspend_s3 img_uuid=$img_uuid img_path=$img_path
	initrd (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
}

#menuentry "ChromeOS (settings)" --class "brunch-settings" {
#	img_part=/dev/sda13
#	img_path=/chromeos.img
#	img_uuid=03d60467-4cc2-405d-8c77-23b09c1a8380
#	search --no-floppy --set=root --file $img_path
#	loopback loop $img_path
#	source (loop,12)/efi/boot/settings.cfg
#	linux (loop,7)/kernel boot=local noresume noswap loglevel=7 options= chromeos_bootsplash= edit_brunch_config=1 \
#		cros_secure cros_debug img_uuid=$img_uuid img_path=$img_path
#	initrd (loop,7)/lib/firmware/intel-ucode.img (loop,7)/initramfs.img
#}
