#! /bin/sh

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
#
#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -AlF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#### disk usage ####
alias du1='du -cxhd1'
alias du5='du -cxhd1 --all -t50M'

#### rsync ####

function rs_cp() { #copy-overwrite dest if different regardless
    rsync -hh --info=stats1,progress2 --modify-window=2 -aHAX "$@"
}

function rs_up() { #copy-update do not overwrite newer on dest
    rsync -hh --info=stats1,progress2 --modify-window=2 -aHAX --update "$@"
}

function rs_cl() { #copy-clone by removing extra dest files
    rsync -hh --info=stats1,progress2 --modify-window=2 -aHAX --delete "$@"
}

function rs_mv { #move by removing source files
    rsync -hh --info=stats1,progress2 --modify-window=2 -aHAX --remove-source-files "$@"
}

#function rs_sys { #full system filesystem backup
#
#

#### zfs list,mount,move ####

alias zls='zfs list -o name,used,referenced,canmount,mounted,mountpoint'

function zlm() {
    zfs list -o name,used,referenced,canmount,mounted,mountpoint $@ | egrep -e ' on ' -e ' yes '
}

function zlz() {
    zfs get -o name,property,value $@ all | egrep -e 'com\.ubuntu\.zsys'
}

alias zm='mount -t zfs -o zfsutil'
alias zu='umount -t zfs -lf'

# mount -t zfs [-o zfsutil] datasets [recursively] to their name under a root directory
function zma() {
    if [ "$1" = "-R" ]; then
        shift 1
        rooty="$1"
        shift 1
    else
        rooty="/z"
    fi
    fss=$(zfs list -H -o name $@)
    for fs in $fss; do
        derr=$rooty/$fs
        if [ ! "$(cat /proc/self/mounts | egrep -e $derr)" = "" ]; then
            continue
        fi
        if [ ! -d $derr ]; then
            mkdir -p $derr
        fi
        if [ "$(zfs list -H -o mountpoint $fs)" = "legacy" ]; then
            mount -t zfs $fs $derr
        else
            mount -t zfs -o zfsutil $fs $derr
        fi
        echo "Mounted $fs on $derr"
    done
}

# umount -t zfs datasets [recursively] with force and remove mountpoints
function zua() {
    if [ "$1" = "-R" ]; then
        shift 1
        rooty="$1"
        shift 1
    else
        rooty="/z"
    fi
    fss=$(zfs list -H -o name $@ | tac)
    # reverses output so unmount in order
    for fs in $fss; do
        derr=$rooty/$fs
        while [ "$(cat /proc/self/mounts | egrep -e $derr)" ]; do
             umount -t zfs $fs $derr 2> /dev/null
             umount -lf $derr 2> /dev/null
        done
    rm -r $derr 2> /dev/null
    echo "Unmounted $fs and removed $derr"
    done
}

#### take a manual zfs snap of mounted datasets
function zsnap() {
    dstamp=$(date +%Y%m%d.%H%M)
    if [ "$1" ]; then
        nom="$1-$dstamp"
    else
        nom="manual-$dstamp"
    fi
    dss=$(zfs mount | awk '{ print $1 }')
    for ds in $dss; do
        zfs snapshot $ds@$nom
    done
}

#### repace spaces with underscore ####
function underscore() {
#    if [ "$1" ]; then maxd="$1"; else maxd=20; fi
    for i in {1..18}; do
        find ./ -mindepth $i -maxdepth $i -path "* *" -print0 | xargs -0 rename 'y/ /_/'
    done
}
